version: "3.8"

volumes:
  src_volume:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - src_volume:/app:rw
